### ISSUE TITLE
Lazy services with factories

### ISSUE THREAD

**Issue by metanav** [zendframework/zend-servicemanager#118] opened 2016-05-12 16:03 UTC
I am using a lazy service but I guess proxy is not being generated correctly. Or, I am missing some basic things. I have created a gist: https://gist.github.com/metanav/0017ee8b3171e079be2fc165ccf69ac9

**Comment by Ocramius** [comment] 2016-05-12 16:10
What is the outcome? Btw, the class map seems incorrect: should map from
service name to expected instance type, not to factories.

**Comment by metanav** [comment] 2016-05-12 16:55
it throws the error:
Fatal error: Call to undefined method ProxyManagerGeneratedProxy\__PM__\SocialAuth\Adapter\Factory\HybridAuthAdapterFactory\Generatedc168519a10309fef32fc623cefbfddd3::authenticate()

I have modified the class_map (see the updated gist) and seems working. Just wondering how the proxy manager calls the factory and inject dependencies to the instance?

**Comment by metanav** [comment] 2016-05-12 17:08
Also, how to know whether the generated proxy can call the real object? Suppose for some reason real object creation gets failed due to some exception and it is set as null in proxy. How can be check if it is null?

**Comment by Ocramius** [comment] 2016-05-13 06:59
> I have modified the class_map (see the updated gist) and seems working.

So the issue is fixed?

 > Just wondering how the proxy manager calls the factory and inject dependencies to the instance? 

That is a bit more advanced: you will need to read the [ProxyManager documentation](https://github.com/Ocramius/ProxyManager/tree/2.0.1/docs). You can also read further in https://github.com/Ocramius/ProxyManager/tree/2.0.1/docs

 > Also, how to know whether the generated proxy can call the real object? Suppose for some reason real object creation gets failed due to some exception and it is set as null in proxy. How can be checked if it is null? 

This is a very good point, and I don't think that ProxyManager provides any utility to check that at the moment. Could you open an issue on ProxyManager with a possible failure scenario (once you caught up on the docs for it)?

**Comment by Ocramius** [comment] 2016-05-13 06:59
Closing here, since the question turned out to be a misconfiguration issue.

**Closed by Ocramius** 2016-05-13 06:59 UTC
Labels: inapplicable, question
